### ISSUE TITLE
希望可以转出更多格式

### ISSUE THREAD

**Issue by booshitassassin** [Majjcom/ncmpp#4]
大大的工具非常实用，可以很快的解码，非常感谢！！！
但是如果可以保留原本的FLAC的音源解码，而不只是转换成mp3就好了（我猜测这会非常有难度，有劳大大！）

**Comment by Majjcom** [comment]
本软件是把ncm内部加密的音频源解密，音频格式由ncm内部的格式决定。所以解密的文件只有MP3的原因只是ncm本身就都是mp3格式的。
我自己下的ncm解密的文件有MP3也有FLAC。
推荐使用[ncmppGui](https://github.com/Majjcom/ncmppGui)来解密

**Comment by booshitassassin** [comment]
okok，一开始没发现我的下载设置的不是flac，不好意思OvO,已经解决了谢谢大佬
